// ----------------------------------------------------------------------------
// AUTO-GENERATED by tools/codegen.py -- DO NOT EDIT
// Source:    spec_validate/ni_function_blocks.json
// Source SHA: 52b5907c128a
// Generator version: v1.0.0
// Generated at: 2026-05-27T02:53:50Z
// ----------------------------------------------------------------------------
#pragma once
#include <cstdint>

namespace ni {
namespace blocks {

// --- function block inventory ---
enum class FunctionBlock {
  NMU,
  NSU,
};

// --- per-feature mode enums ---
enum class AXI_SLAVE_PORTMode {
  Active,
  Passive,
};
enum class ADDR_TRANSMode {
  XYRouting,
  SourceRouting,
  IDRouting,
};
enum class QOS_GENMode {
  Bypass,
  Fixed,
  Limiter,
  Regulator,
};
enum class ROBMode {
  NoRoB,
  SimpleRoB,
  NormalRoB,
};
enum class AXI_MASTER_PORTMode {
  Active,
  Passive,
};

// --- compile-time parameters ---
constexpr int CUT_AX = 0;
constexpr int CUT_RSP = 0;
// ROUTE_ALGO = "XYRouting"  (string param, no C++ constexpr)
constexpr int USE_ID_TABLE = 0;
constexpr int XY_ADDR_OFFSET_X = 32;
constexpr int XY_ADDR_OFFSET_Y = 36;
constexpr int MESH_COLS = 4;
constexpr int MESH_ROWS = 4;
constexpr int NUM_SAM_RULES = 8;
constexpr int MAX_TXNS = 32;
constexpr int MAX_TXNS_PER_ID = 8;
// B_ROB_TYPE = "NoRoB"  (string param, no C++ constexpr)
// R_ROB_TYPE = "NoRoB"  (string param, no C++ constexpr)
constexpr int B_ROB_SIZE = 32;
constexpr int R_ROB_SIZE = 32;
constexpr int ONLY_METADATA_B = 1;
constexpr int NMU_BUFFER_DEPTH = 2;
constexpr int NMU_CDC_FIFO_DEPTH = 16;
constexpr int NSU_CUT_AX = 0;
constexpr int NSU_CUT_RSP = 0;
constexpr int NSU_MAX_TXNS = 32;
constexpr int EXCLUSIVE_MONITOR_DEPTH = 8;
constexpr int NSU_R_BUFFER_DEPTH = 16;
constexpr int NSU_CDC_FIFO_DEPTH = 16;

}  // namespace blocks
}  // namespace ni
