// ----------------------------------------------------------------------------
// AUTO-GENERATED by tools/codegen.py -- DO NOT EDIT
// Source:    spec_validate/generated/ni_registers.json
// Source SHA: 05cc59c20bff
// Generator version: v1.0.0
// Generated at: 2026-05-27T06:13:01Z
// ----------------------------------------------------------------------------
#pragma once
#include <cstdint>

namespace ni {
namespace regs {

// --- register offsets ---
constexpr int PKT_PROBE_EN_OFFSET = 0x40;
constexpr int PKT_PROBE_MODE_OFFSET = 0x44;
constexpr int PKT_WINDOW_SIZE_OFFSET = 0x48;
constexpr int PKT_BYTE_COUNT_OFFSET = 0x4c;
constexpr int PKT_BANDWIDTH_OFFSET = 0x50;
constexpr int TXN_PROBE_EN_OFFSET = 0x60;
constexpr int TXN_THRESHOLD_0_OFFSET = 0x64;
constexpr int TXN_THRESHOLD_1_OFFSET = 0x68;
constexpr int TXN_THRESHOLD_2_OFFSET = 0x6c;
constexpr int TXN_THRESHOLD_3_OFFSET = 0x70;
constexpr int TXN_BIN_0_COUNT_OFFSET = 0x80;
constexpr int TXN_BIN_1_COUNT_OFFSET = 0x84;
constexpr int TXN_BIN_2_COUNT_OFFSET = 0x88;
constexpr int TXN_BIN_3_COUNT_OFFSET = 0x8c;
constexpr int TXN_BIN_4_COUNT_OFFSET = 0x90;
constexpr int TXN_MIN_LATENCY_OFFSET = 0x94;
constexpr int TXN_MAX_LATENCY_OFFSET = 0x98;
constexpr int TXN_TOTAL_COUNT_OFFSET = 0x9c;
constexpr int ERR_STATUS_OFFSET = 0x100;
constexpr int ECC_UNCORR_ERR_CNT_OFFSET = 0x108;
constexpr int LAST_ERR_INFO_OFFSET = 0x10c;
constexpr int IRQ_ENABLE_OFFSET = 0x114;
constexpr int ECC_CORR_ERR_CNT_OFFSET = 0x118;
constexpr int ROUTE_PAR_ERR_CNT_OFFSET = 0x11c;
constexpr int AXI_PARITY_ERR_CNT_OFFSET = 0x120;
constexpr int PENDING_R_COUNT_OFFSET = 0x130;
constexpr int PENDING_W_COUNT_OFFSET = 0x134;
constexpr int QUIESCE_CTRL_OFFSET = 0x13c;
constexpr int QUIESCE_STATUS_OFFSET = 0x140;
constexpr int EXCLUSIVE_MONITOR_CTRL_OFFSET = 0x144;
constexpr int EXCLUSIVE_MONITOR_STATUS_OFFSET = 0x148;

// --- field bit masks ---
constexpr int ERR_STATUS_ECC_UNCORR_ERR_MASK = 0x1;
constexpr int ERR_STATUS_ROUTE_PAR_ERR_MASK = 0x2;
constexpr int ERR_STATUS_AXI_PARITY_ERR_MASK = 0x4;
constexpr int LAST_ERR_INFO_ERR_AXI_ID_MASK = 0xff;
constexpr int LAST_ERR_INFO_ERR_SRC_ID_MASK = 0xff00;
constexpr int LAST_ERR_INFO_ERR_DST_ID_MASK = 0xff0000;
constexpr int IRQ_ENABLE_ECC_UNCORR_IRQ_EN_MASK = 0x1;
constexpr int IRQ_ENABLE_ROUTE_PAR_IRQ_EN_MASK = 0x2;
constexpr int IRQ_ENABLE_AXI_PARITY_IRQ_EN_MASK = 0x4;
constexpr int QUIESCE_CTRL_QUIESCE_REQ_MASK = 0x1;
constexpr int QUIESCE_STATUS_QUIESCE_IDLE_MASK = 0x1;
constexpr int EXCLUSIVE_MONITOR_CTRL_CLEAR_ALL_MASK = 0x1;

// --- access mode enums (one per register) ---
enum class PKT_PROBE_ENAccess { RW };
enum class PKT_PROBE_MODEAccess { RW };
enum class PKT_WINDOW_SIZEAccess { RW };
enum class PKT_BYTE_COUNTAccess { RO };
enum class PKT_BANDWIDTHAccess { RO };
enum class TXN_PROBE_ENAccess { RW };
enum class TXN_THRESHOLD_0Access { RW };
enum class TXN_THRESHOLD_1Access { RW };
enum class TXN_THRESHOLD_2Access { RW };
enum class TXN_THRESHOLD_3Access { RW };
enum class TXN_BIN_0_COUNTAccess { RO };
enum class TXN_BIN_1_COUNTAccess { RO };
enum class TXN_BIN_2_COUNTAccess { RO };
enum class TXN_BIN_3_COUNTAccess { RO };
enum class TXN_BIN_4_COUNTAccess { RO };
enum class TXN_MIN_LATENCYAccess { RO };
enum class TXN_MAX_LATENCYAccess { RO };
enum class TXN_TOTAL_COUNTAccess { RO };
enum class ERR_STATUSAccess { RW1C };
enum class ECC_UNCORR_ERR_CNTAccess { RO };
enum class LAST_ERR_INFOAccess { RO };
enum class IRQ_ENABLEAccess { RW };
enum class ECC_CORR_ERR_CNTAccess { RO };
enum class ROUTE_PAR_ERR_CNTAccess { RO };
enum class AXI_PARITY_ERR_CNTAccess { RO };
enum class PENDING_R_COUNTAccess { RO };
enum class PENDING_W_COUNTAccess { RO };
enum class QUIESCE_CTRLAccess { RW };
enum class QUIESCE_STATUSAccess { RO };
enum class EXCLUSIVE_MONITOR_CTRLAccess { WO };
enum class EXCLUSIVE_MONITOR_STATUSAccess { RO };

// --- static_assert: per-register field width sum <= data_width (design doc sec 6.4) ---
static_assert(3 <= 32, "ERR_STATUS: field width sum (3) must be <= data_width (32)");
static_assert(24 <= 32, "LAST_ERR_INFO: field width sum (24) must be <= data_width (32)");
static_assert(3 <= 32, "IRQ_ENABLE: field width sum (3) must be <= data_width (32)");
static_assert(1 <= 32, "QUIESCE_CTRL: field width sum (1) must be <= data_width (32)");
static_assert(1 <= 32, "QUIESCE_STATUS: field width sum (1) must be <= data_width (32)");
static_assert(1 <= 32, "EXCLUSIVE_MONITOR_CTRL: field width sum (1) must be <= data_width (32)");

}  // namespace regs
}  // namespace ni
