// ----------------------------------------------------------------------------
// AUTO-GENERATED by tools/codegen.py -- DO NOT EDIT
// Source:    spec_validate/generated/ni_signals.json
// Source SHA: f9a618f8ffa8
// Generator version: v1.0.0
// Generated at: 2026-05-27T05:32:50Z
// ----------------------------------------------------------------------------
#pragma once
#include <cstdint>

namespace ni {
namespace signals {

// Reset initializer constants for output signals.
// Input signals (external_driven) have no reset value defined here.

constexpr int AXI_BID_O_RESET = 0;
constexpr int AXI_BRESP_O_RESET = 0;
constexpr int AXI_BUSER_O_RESET = 0;
constexpr int AXI_RID_O_RESET = 0;
constexpr int AXI_RDATA_O_RESET = 0;
constexpr int AXI_RRESP_O_RESET = 0;
constexpr int AXI_RLAST_O_RESET = 0;
constexpr int AXI_RUSER_O_RESET = 0;
constexpr int NOC_REQ_VALID_O_RESET = 0;
constexpr int NOC_REQ_FLIT_O_RESET = 0;
constexpr int NOC_RSP_CREDIT_O_RESET = 0;
constexpr int CSR_BID_O_RESET = 0;
constexpr int CSR_BRESP_O_RESET = 0;
constexpr int CSR_BUSER_O_RESET = 0;
constexpr int CSR_RID_O_RESET = 0;
constexpr int CSR_RDATA_O_RESET = 0;
constexpr int CSR_RRESP_O_RESET = 0;
constexpr int CSR_RLAST_O_RESET = 0;
constexpr int CSR_RUSER_O_RESET = 0;
constexpr int NOC_REQ_CREDIT_O_RESET = 0;
constexpr int AXI_AWID_O_RESET = 0;
constexpr int AXI_AWADDR_O_RESET = 0;
constexpr int AXI_AWLEN_O_RESET = 0;
constexpr int AXI_AWSIZE_O_RESET = 0;
constexpr int AXI_AWBURST_O_RESET = 0;
constexpr int AXI_AWCACHE_O_RESET = 0;
constexpr int AXI_AWLOCK_O_RESET = 0;
constexpr int AXI_AWPROT_O_RESET = 0;
constexpr int AXI_AWREGION_O_RESET = 0;
constexpr int AXI_AWUSER_O_RESET = 0;
constexpr int AXI_AWQOS_O_RESET = 0;
constexpr int AXI_WDATA_O_RESET = 0;
constexpr int AXI_WSTRB_O_RESET = 0;
constexpr int AXI_WLAST_O_RESET = 0;
constexpr int AXI_WUSER_O_RESET = 0;
constexpr int AXI_ARID_O_RESET = 0;
constexpr int AXI_ARADDR_O_RESET = 0;
constexpr int AXI_ARLEN_O_RESET = 0;
constexpr int AXI_ARSIZE_O_RESET = 0;
constexpr int AXI_ARBURST_O_RESET = 0;
constexpr int AXI_ARCACHE_O_RESET = 0;
constexpr int AXI_ARLOCK_O_RESET = 0;
constexpr int AXI_ARPROT_O_RESET = 0;
constexpr int AXI_ARREGION_O_RESET = 0;
constexpr int AXI_ARUSER_O_RESET = 0;
constexpr int AXI_ARQOS_O_RESET = 0;
constexpr int NOC_RSP_VALID_O_RESET = 0;
constexpr int NOC_RSP_FLIT_O_RESET = 0;

}  // namespace signals
}  // namespace ni
