"""Codegen SV emitter tests -- Task 8.

Tests cover:
- --target sv --domain {packet|signals|registers|blocks} each produces a .sv file.
- Each .sv file has the correct package / endpackage structure.
- typedef enum logic present in blocks output (design doc sec 6.2 strong typing).
- localparam int unsigned present in all 4 files.
- Provenance banner (AUTO-GENERATED, Source SHA, Generator version, Generated at).
- ifndef/define/endif include guard in all 4 files.
- --check mode covers SV files (detects drift, passes when clean).
- --lint-sv skips gracefully when verilator is not in PATH.
"""
from __future__ import annotations
import shutil
import subprocess
import sys
from pathlib import Path

import pytest

SPEC_VALIDATE = Path(__file__).resolve().parent.parent
CODEGEN = SPEC_VALIDATE / "tools" / "codegen.py"
RTL_PKG_DIR = SPEC_VALIDATE / "rtl_pkg"


def run_codegen(*args: str) -> subprocess.CompletedProcess:
    return subprocess.run(
        [sys.executable, str(CODEGEN), *args],
        capture_output=True,
        text=True,
        cwd=str(SPEC_VALIDATE),
    )


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _sv_text(filename: str) -> str:
    """Read committed SV file (regenerate first to ensure it exists)."""
    path = RTL_PKG_DIR / filename
    if not path.exists():
        pytest.skip(f"{filename} not found; run --target sv first")
    return path.read_text(encoding="ascii")


# ---------------------------------------------------------------------------
# Emit tests -- one per domain
# ---------------------------------------------------------------------------

class TestSvPacketEmit:
    def setup_method(self):
        r = run_codegen("--target", "sv", "--domain", "packet",
                        "--out", str(RTL_PKG_DIR))
        assert r.returncode == 0, r.stderr

    def test_exits_zero(self):
        r = run_codegen("--target", "sv", "--domain", "packet",
                        "--out", str(RTL_PKG_DIR))
        assert r.returncode == 0, r.stderr

    def test_file_exists(self):
        assert (RTL_PKG_DIR / "ni_flit_pkg.sv").exists()

    def test_package_structure(self):
        text = _sv_text("ni_flit_pkg.sv")
        assert "package ni_flit_pkg;" in text
        assert "endpackage" in text

    def test_localparam_int_unsigned(self):
        text = _sv_text("ni_flit_pkg.sv")
        assert "localparam int unsigned" in text

    def test_flit_width_constant(self):
        text = _sv_text("ni_flit_pkg.sv")
        assert "FLIT_WIDTH" in text

    def test_header_field_lsb_msb(self):
        text = _sv_text("ni_flit_pkg.sv")
        assert "ROB_IDX_LSB" in text
        assert "ROB_IDX_MSB" in text

    def test_ifndef_include_guard(self):
        text = _sv_text("ni_flit_pkg.sv")
        assert "`ifndef NI_FLIT_PKG_SVH" in text
        assert "`define NI_FLIT_PKG_SVH" in text
        assert "`endif" in text

    def test_provenance_banner(self):
        text = _sv_text("ni_flit_pkg.sv")
        assert "AUTO-GENERATED by tools/codegen.py" in text
        assert "Source SHA:" in text
        assert "Generator version:" in text
        assert "Generated at:" in text


class TestSvSignalsEmit:
    def setup_method(self):
        r = run_codegen("--target", "sv", "--domain", "signals",
                        "--out", str(RTL_PKG_DIR))
        assert r.returncode == 0, r.stderr

    def test_exits_zero(self):
        r = run_codegen("--target", "sv", "--domain", "signals",
                        "--out", str(RTL_PKG_DIR))
        assert r.returncode == 0, r.stderr

    def test_file_exists(self):
        assert (RTL_PKG_DIR / "ni_signals_pkg.sv").exists()

    def test_package_structure(self):
        text = _sv_text("ni_signals_pkg.sv")
        assert "package ni_signals_pkg;" in text
        assert "endpackage" in text

    def test_localparam_int_unsigned(self):
        text = _sv_text("ni_signals_pkg.sv")
        # Either contains a constant OR explains there are no reset values.
        assert "localparam int unsigned" in text or "No output signals" in text

    def test_ifndef_include_guard(self):
        text = _sv_text("ni_signals_pkg.sv")
        assert "`ifndef NI_SIGNALS_PKG_SVH" in text
        assert "`define NI_SIGNALS_PKG_SVH" in text
        assert "`endif" in text

    def test_provenance_banner(self):
        text = _sv_text("ni_signals_pkg.sv")
        assert "Source SHA:" in text


class TestSvRegistersEmit:
    def setup_method(self):
        r = run_codegen("--target", "sv", "--domain", "registers",
                        "--out", str(RTL_PKG_DIR))
        assert r.returncode == 0, r.stderr

    def test_exits_zero(self):
        r = run_codegen("--target", "sv", "--domain", "registers",
                        "--out", str(RTL_PKG_DIR))
        assert r.returncode == 0, r.stderr

    def test_file_exists(self):
        assert (RTL_PKG_DIR / "ni_regs_pkg.sv").exists()

    def test_package_structure(self):
        text = _sv_text("ni_regs_pkg.sv")
        assert "package ni_regs_pkg;" in text
        assert "endpackage" in text

    def test_localparam_int_unsigned_offsets(self):
        text = _sv_text("ni_regs_pkg.sv")
        assert "localparam int unsigned" in text
        assert "_OFFSET" in text

    def test_ifndef_include_guard(self):
        text = _sv_text("ni_regs_pkg.sv")
        assert "`ifndef NI_REGS_PKG_SVH" in text
        assert "`define NI_REGS_PKG_SVH" in text
        assert "`endif" in text

    def test_provenance_banner(self):
        text = _sv_text("ni_regs_pkg.sv")
        assert "Source SHA:" in text


class TestSvBlocksEmit:
    def setup_method(self):
        r = run_codegen("--target", "sv", "--domain", "blocks",
                        "--out", str(RTL_PKG_DIR))
        assert r.returncode == 0, r.stderr

    def test_exits_zero(self):
        r = run_codegen("--target", "sv", "--domain", "blocks",
                        "--out", str(RTL_PKG_DIR))
        assert r.returncode == 0, r.stderr

    def test_file_exists(self):
        assert (RTL_PKG_DIR / "ni_blocks_pkg.sv").exists()

    def test_package_structure(self):
        text = _sv_text("ni_blocks_pkg.sv")
        assert "package ni_blocks_pkg;" in text
        assert "endpackage" in text

    def test_typedef_enum_logic(self):
        """SV enums must use typedef enum logic (design doc sec 6.2 strong typing)."""
        text = _sv_text("ni_blocks_pkg.sv")
        assert "typedef enum logic" in text

    def test_function_block_enum(self):
        text = _sv_text("ni_blocks_pkg.sv")
        assert "function_block_e" in text
        assert "NMU" in text
        assert "NSU" in text

    def test_rob_mode_enum(self):
        """ROB mode enum should be present with NOROB variant."""
        text = _sv_text("ni_blocks_pkg.sv")
        assert "rob_mode_e" in text
        assert "ROB_MODE_NOROB" in text

    def test_localparam_int_unsigned_compile_params(self):
        text = _sv_text("ni_blocks_pkg.sv")
        assert "localparam int unsigned" in text

    def test_ifndef_include_guard(self):
        text = _sv_text("ni_blocks_pkg.sv")
        assert "`ifndef NI_BLOCKS_PKG_SVH" in text
        assert "`define NI_BLOCKS_PKG_SVH" in text
        assert "`endif" in text

    def test_provenance_banner(self):
        text = _sv_text("ni_blocks_pkg.sv")
        assert "Source SHA:" in text


# ---------------------------------------------------------------------------
# --check mode covers SV files
# ---------------------------------------------------------------------------

class TestCheckModeWithSv:
    def setup_method(self):
        """Ensure all SV files are freshly generated before each check test."""
        for domain in ("packet", "signals", "registers", "blocks"):
            run_codegen("--target", "sv", "--domain", domain, "--out", str(RTL_PKG_DIR))
        # Also ensure C++ headers are fresh.
        from tests.test_codegen import INCLUDE_DIR
        for domain in ("packet", "signals", "registers", "blocks"):
            run_codegen("--target", "cpp", "--domain", domain, "--out", str(INCLUDE_DIR))

    def test_check_exits_zero_when_sv_clean(self):
        """--check must exit 0 when all SV files match fresh regen."""
        r = run_codegen("--check")
        assert r.returncode == 0, (
            f"--check should exit 0 when SV files are fresh.\n"
            f"stdout: {r.stdout}\nstderr: {r.stderr}"
        )

    def test_check_exits_one_on_sv_drift(self):
        """--check must exit 1 when a committed SV file has drifted."""
        target_sv = RTL_PKG_DIR / "ni_flit_pkg.sv"
        original_text = target_sv.read_text(encoding="ascii")
        try:
            drifted = original_text + "\n// DRIFT INJECTED FOR TEST\n"
            target_sv.write_text(drifted, encoding="ascii")
            r = run_codegen("--check")
            assert r.returncode == 1, "--check should exit 1 when SV has drifted"
        finally:
            target_sv.write_text(original_text, encoding="ascii")


# ---------------------------------------------------------------------------
# --lint-sv graceful skip
# ---------------------------------------------------------------------------

class TestLintSv:
    def test_lint_sv_graceful_skip_or_pass(self):
        """--lint-sv must exit 0 (either skip or lint pass; never crash)."""
        # First ensure SV files exist.
        for domain in ("packet", "signals", "registers", "blocks"):
            run_codegen("--target", "sv", "--domain", domain, "--out", str(RTL_PKG_DIR))

        r = run_codegen("--lint-sv")
        # Either 0 (skip or pass) or non-zero only if verilator found a real lint error.
        # Since we can't guarantee verilator outcome on all CI envs, we just confirm
        # it doesn't crash with an exception (non-zero return from subprocess == lint warning).
        # The requirement is that absence of verilator exits 0, not that lint is perfect.
        if shutil.which("verilator") is None:
            assert r.returncode == 0, (
                f"--lint-sv must exit 0 when verilator not in PATH.\n"
                f"stderr: {r.stderr}"
            )
            assert "skip" in r.stderr.lower(), (
                f"Expected [skip] message in stderr when verilator absent.\n"
                f"stderr: {r.stderr}"
            )
        # If verilator IS present, returncode may be 0 or non-zero depending on
        # lint warnings -- we just verify the command ran without Python exceptions.
        assert "Traceback" not in r.stderr, (
            f"--lint-sv raised a Python exception:\n{r.stderr}"
        )

    def test_lint_sv_no_python_exception_without_verilator(self, monkeypatch):
        """Simulate verilator missing by overriding PATH, confirm graceful skip."""
        import os
        env = os.environ.copy()
        env["PATH"] = ""  # empty PATH -> shutil.which("verilator") returns None
        result = subprocess.run(
            [sys.executable, str(CODEGEN), "--lint-sv"],
            capture_output=True,
            text=True,
            env=env,
            cwd=str(SPEC_VALIDATE),
        )
        assert result.returncode == 0, f"Expected exit 0, got {result.returncode}.\nstderr: {result.stderr}"
        assert "skip" in result.stderr.lower(), (
            f"Expected skip message.\nstderr: {result.stderr}"
        )
