// ----------------------------------------------------------------------------
// AUTO-GENERATED by tools/codegen.py -- DO NOT EDIT
// Source:    spec_validate/ni_function_blocks.json
// Source SHA: d930c931df03
// Generator version: v1.0.0
// Generated at: 2026-05-27T03:44:05Z
// ----------------------------------------------------------------------------
`ifndef NI_BLOCKS_PKG_SVH
`define NI_BLOCKS_PKG_SVH

package ni_blocks_pkg;

  // --- function block inventory ---
  typedef enum logic [0:0] {
    NMU = 1'd0,
    NSU = 1'd1
  } function_block_e;

  // --- per-feature mode enums ---
  typedef enum logic [0:0] {
    AXI_SLAVE_PORT_MODE_ACTIVE = 1'd0,
    AXI_SLAVE_PORT_MODE_PASSIVE = 1'd1
  } axi_slave_port_mode_e;
  typedef enum logic [1:0] {
    ADDR_TRANS_MODE_XYROUTING = 2'd0,
    ADDR_TRANS_MODE_SOURCEROUTING = 2'd1,
    ADDR_TRANS_MODE_IDROUTING = 2'd2
  } addr_trans_mode_e;
  typedef enum logic [1:0] {
    ROB_MODE_NOROB = 2'd0,
    ROB_MODE_SIMPLEROB = 2'd1,
    ROB_MODE_NORMALROB = 2'd2
  } rob_mode_e;
  typedef enum logic [0:0] {
    VC_ARB_MODE_ROUNDROBIN = 1'd0
  } vc_arb_mode_e;
  typedef enum logic [0:0] {
    AXI_MASTER_PORT_MODE_ACTIVE = 1'd0,
    AXI_MASTER_PORT_MODE_PASSIVE = 1'd1
  } axi_master_port_mode_e;
  typedef enum logic [0:0] {
    VC_ARB_MODE_ROUNDROBIN = 1'd0
  } vc_arb_mode_e;

  // --- compile-time parameters ---
  localparam int unsigned CUT_AX = 0;
  localparam int unsigned CUT_RSP = 0;
  // ROUTE_ALGO = "XYRouting"  (string param, no SV localparam)
  localparam int unsigned USE_ID_TABLE = 0;
  localparam int unsigned XY_ADDR_OFFSET_X = 32;
  localparam int unsigned XY_ADDR_OFFSET_Y = 36;
  localparam int unsigned MESH_COLS = 4;
  localparam int unsigned MESH_ROWS = 4;
  localparam int unsigned NUM_SAM_RULES = 8;
  localparam int unsigned MAX_TXNS = 32;
  localparam int unsigned MAX_TXNS_PER_ID = 8;
  // B_ROB_TYPE = "NoRoB"  (string param, no SV localparam)
  // R_ROB_TYPE = "NoRoB"  (string param, no SV localparam)
  localparam int unsigned B_ROB_SIZE = 32;
  localparam int unsigned R_ROB_SIZE = 32;
  localparam int unsigned ONLY_METADATA_B = 1;
  localparam int unsigned NMU_BUFFER_DEPTH = 2;
  localparam int unsigned NMU_CDC_FIFO_DEPTH = 16;
  localparam int unsigned NSU_CUT_AX = 0;
  localparam int unsigned NSU_CUT_RSP = 0;
  localparam int unsigned NSU_MAX_TXNS = 32;
  localparam int unsigned EXCLUSIVE_MONITOR_DEPTH = 8;
  localparam int unsigned NSU_R_BUFFER_DEPTH = 16;
  localparam int unsigned NSU_CDC_FIFO_DEPTH = 16;

endpackage

`endif // NI_BLOCKS_PKG_SVH
