// ----------------------------------------------------------------------------
// AUTO-GENERATED by tools/codegen.py -- DO NOT EDIT
// Source:    spec_validate/generated/ni_packet.json
// Source SHA: 6067d8f1cc7e
// Generator version: v1.0.0
// Generated at: 2026-05-27T03:08:40Z
// ----------------------------------------------------------------------------
`ifndef NI_FLIT_PKG_SVH
`define NI_FLIT_PKG_SVH

package ni_flit_pkg;

  // --- top-level flit widths (from flit.derived) ---
  localparam int unsigned FLIT_WIDTH        = 406;
  localparam int unsigned HEADER_WIDTH      = 54;
  localparam int unsigned PAYLOAD_WIDTH     = 352;
  localparam int unsigned LINK_WIDTH        = 407;
  localparam int unsigned FLIT_DATA_WIDTH = 396;
  localparam int unsigned HEADER_DATA_WIDTH = 44;
  localparam int unsigned WSTRB_WIDTH     = 32;

  // --- header field bit positions (from flit.header_fields) ---
  localparam int unsigned NOC_QOS_LSB   = 0;
  localparam int unsigned NOC_QOS_MSB   = 3;
  localparam int unsigned NOC_QOS_WIDTH = 4;
  localparam int unsigned AXI_CH_LSB   = 4;
  localparam int unsigned AXI_CH_MSB   = 6;
  localparam int unsigned AXI_CH_WIDTH = 3;
  localparam int unsigned SRC_ID_LSB   = 7;
  localparam int unsigned SRC_ID_MSB   = 14;
  localparam int unsigned SRC_ID_WIDTH = 8;
  localparam int unsigned DST_ID_LSB   = 15;
  localparam int unsigned DST_ID_MSB   = 22;
  localparam int unsigned DST_ID_WIDTH = 8;
  localparam int unsigned VC_ID_LSB   = 23;
  localparam int unsigned VC_ID_MSB   = 25;
  localparam int unsigned VC_ID_WIDTH = 3;
  localparam int unsigned ROUTE_PAR_LSB   = 26;
  localparam int unsigned ROUTE_PAR_MSB   = 26;
  localparam int unsigned ROUTE_PAR_WIDTH = 1;
  localparam int unsigned LAST_LSB   = 27;
  localparam int unsigned LAST_MSB   = 27;
  localparam int unsigned LAST_WIDTH = 1;
  localparam int unsigned ROB_REQ_LSB   = 28;
  localparam int unsigned ROB_REQ_MSB   = 28;
  localparam int unsigned ROB_REQ_WIDTH = 1;
  localparam int unsigned ROB_IDX_LSB   = 29;
  localparam int unsigned ROB_IDX_MSB   = 33;
  localparam int unsigned ROB_IDX_WIDTH = 5;
  localparam int unsigned RSVD_COMMTYPE_LSB   = 34;
  localparam int unsigned RSVD_COMMTYPE_MSB   = 35;
  localparam int unsigned RSVD_COMMTYPE_WIDTH = 2;
  localparam int unsigned MULTICAST_LSB   = 36;
  localparam int unsigned MULTICAST_MSB   = 43;
  localparam int unsigned MULTICAST_WIDTH = 8;
  localparam int unsigned FLIT_ECC_LSB   = 44;
  localparam int unsigned FLIT_ECC_MSB   = 53;
  localparam int unsigned FLIT_ECC_WIDTH = 10;

  // --- payload widths per channel (from flit.payload_channels) ---
  localparam int unsigned AW_WIDTH = 108;
  localparam int unsigned AR_WIDTH = 108;
  localparam int unsigned W_WIDTH = 352;
  localparam int unsigned B_WIDTH = 64;
  localparam int unsigned R_WIDTH = 352;

  // --- all field widths (from flit.field_widths) ---
  localparam int unsigned X_WIDTH                = 4;
  localparam int unsigned Y_WIDTH                = 4;
  localparam int unsigned NOC_QOS_WIDTH          = 4;
  localparam int unsigned AXI_CH_WIDTH           = 3;
  localparam int unsigned LAST_WIDTH             = 1;
  localparam int unsigned ROB_REQ_WIDTH          = 1;
  localparam int unsigned ROB_IDX_WIDTH          = 5;
  localparam int unsigned RSVD_COMMTYPE_WIDTH    = 2;
  localparam int unsigned MULTICAST_WIDTH        = 8;
  localparam int unsigned VC_ID_WIDTH            = 3;
  localparam int unsigned ROUTE_PAR_WIDTH        = 1;
  localparam int unsigned FLIT_ECC_WIDTH         = 10;
  localparam int unsigned AXI_ADDR_WIDTH         = 64;
  localparam int unsigned AXI_ID_WIDTH           = 8;
  localparam int unsigned NOC_DATA_WIDTH         = 256;
  localparam int unsigned AXI_USER_WIDTH         = 8;
  localparam int unsigned AXI_LEN_WIDTH          = 8;
  localparam int unsigned AXI_SIZE_WIDTH         = 3;
  localparam int unsigned AXI_BURST_WIDTH        = 2;
  localparam int unsigned AXI_CACHE_WIDTH        = 4;
  localparam int unsigned AXI_LOCK_WIDTH         = 1;
  localparam int unsigned AXI_PROT_WIDTH         = 3;
  localparam int unsigned AXI_REGION_WIDTH       = 4;
  localparam int unsigned AXI_RESP_WIDTH         = 2;
  localparam int unsigned AXI_LAST_WIDTH         = 1;
  localparam int unsigned RSVD_MC_STATUS_WIDTH   = 2;

endpackage

`endif // NI_FLIT_PKG_SVH
