// ----------------------------------------------------------------------------
// AUTO-GENERATED by tools/codegen.py -- DO NOT EDIT
// Source:    spec_validate/generated/ni_registers.json
// Source SHA: bf104cebb46f
// Generator version: v1.0.0
// Generated at: 2026-05-27T03:08:41Z
// ----------------------------------------------------------------------------
`ifndef NI_REGS_PKG_SVH
`define NI_REGS_PKG_SVH

package ni_regs_pkg;

  // --- register offsets ---
  localparam int unsigned QOS_MODE_OFFSET = 0x0;
  localparam int unsigned QOS_FIXED_VALUE_OFFSET = 0x4;
  localparam int unsigned BANDWIDTH_LIMIT_OFFSET = 0x8;
  localparam int unsigned SATURATION_THRESHOLD_OFFSET = 0xc;
  localparam int unsigned LOW_PRIORITY_OFFSET = 0x10;
  localparam int unsigned BANDWIDTH_BUDGET_OFFSET = 0x14;
  localparam int unsigned BASE_QOS_OFFSET = 0x18;
  localparam int unsigned SOCKET_QOS_EN_OFFSET = 0x1c;
  localparam int unsigned SOCKET_QOS_OFFSET = 0x20;
  localparam int unsigned PKT_PROBE_EN_OFFSET = 0x40;
  localparam int unsigned PKT_PROBE_MODE_OFFSET = 0x44;
  localparam int unsigned PKT_WINDOW_SIZE_OFFSET = 0x48;
  localparam int unsigned PKT_BYTE_COUNT_OFFSET = 0x4c;
  localparam int unsigned PKT_BANDWIDTH_OFFSET = 0x50;
  localparam int unsigned TXN_PROBE_EN_OFFSET = 0x60;
  localparam int unsigned TXN_THRESHOLD_0_OFFSET = 0x64;
  localparam int unsigned TXN_THRESHOLD_1_OFFSET = 0x68;
  localparam int unsigned TXN_THRESHOLD_2_OFFSET = 0x6c;
  localparam int unsigned TXN_THRESHOLD_3_OFFSET = 0x70;
  localparam int unsigned TXN_BIN_0_COUNT_OFFSET = 0x80;
  localparam int unsigned TXN_BIN_1_COUNT_OFFSET = 0x84;
  localparam int unsigned TXN_BIN_2_COUNT_OFFSET = 0x88;
  localparam int unsigned TXN_BIN_3_COUNT_OFFSET = 0x8c;
  localparam int unsigned TXN_BIN_4_COUNT_OFFSET = 0x90;
  localparam int unsigned TXN_MIN_LATENCY_OFFSET = 0x94;
  localparam int unsigned TXN_MAX_LATENCY_OFFSET = 0x98;
  localparam int unsigned TXN_TOTAL_COUNT_OFFSET = 0x9c;
  localparam int unsigned ERR_STATUS_OFFSET = 0x100;
  localparam int unsigned ECC_UNCORR_ERR_CNT_OFFSET = 0x108;
  localparam int unsigned LAST_ERR_INFO_OFFSET = 0x10c;
  localparam int unsigned IRQ_ENABLE_OFFSET = 0x114;
  localparam int unsigned ECC_CORR_ERR_CNT_OFFSET = 0x118;
  localparam int unsigned ROUTE_PAR_ERR_CNT_OFFSET = 0x11c;
  localparam int unsigned AXI_PARITY_ERR_CNT_OFFSET = 0x120;
  localparam int unsigned PENDING_R_COUNT_OFFSET = 0x130;
  localparam int unsigned PENDING_W_COUNT_OFFSET = 0x134;
  localparam int unsigned QUIESCE_CTRL_OFFSET = 0x13c;
  localparam int unsigned QUIESCE_STATUS_OFFSET = 0x140;
  localparam int unsigned EXCLUSIVE_MONITOR_CTRL_OFFSET = 0x144;
  localparam int unsigned EXCLUSIVE_MONITOR_STATUS_OFFSET = 0x148;

  // --- field bit masks ---
  localparam int unsigned QOS_MODE_QOS_MODE_MASK = 0x3;
  localparam int unsigned QOS_FIXED_VALUE_QOS_FIXED_VALUE_MASK = 0xf;
  localparam int unsigned BASE_QOS_BASE_QOS_MASK = 0xf;
  localparam int unsigned BASE_QOS_URGENCY_STEP_MASK = 0x30;
  localparam int unsigned ERR_STATUS_ECC_UNCORR_ERR_MASK = 0x1;
  localparam int unsigned ERR_STATUS_ROUTE_PAR_ERR_MASK = 0x2;
  localparam int unsigned ERR_STATUS_AXI_PARITY_ERR_MASK = 0x4;
  localparam int unsigned LAST_ERR_INFO_ERR_AXI_ID_MASK = 0xff;
  localparam int unsigned LAST_ERR_INFO_ERR_SRC_ID_MASK = 0xff00;
  localparam int unsigned LAST_ERR_INFO_ERR_DST_ID_MASK = 0xff0000;
  localparam int unsigned IRQ_ENABLE_ECC_UNCORR_IRQ_EN_MASK = 0x1;
  localparam int unsigned IRQ_ENABLE_ROUTE_PAR_IRQ_EN_MASK = 0x2;
  localparam int unsigned IRQ_ENABLE_AXI_PARITY_IRQ_EN_MASK = 0x4;
  localparam int unsigned QUIESCE_CTRL_QUIESCE_REQ_MASK = 0x1;
  localparam int unsigned QUIESCE_STATUS_QUIESCE_IDLE_MASK = 0x1;
  localparam int unsigned EXCLUSIVE_MONITOR_CTRL_CLEAR_ALL_MASK = 0x1;

endpackage

`endif // NI_REGS_PKG_SVH
