// ----------------------------------------------------------------------------
// AUTO-GENERATED by tools/codegen.py -- DO NOT EDIT
// Source:    spec_validate/generated/ni_signals.json
// Source SHA: f9a618f8ffa8
// Generator version: v1.0.0
// Generated at: 2026-05-27T06:13:01Z
// ----------------------------------------------------------------------------
`ifndef NI_SIGNALS_PKG_SVH
`define NI_SIGNALS_PKG_SVH

package ni_signals_pkg;

  // Reset initializer constants for output signals.
  // Input signals (external_driven) have no reset value defined here.

  localparam int unsigned AXI_BID_O_RESET = 0;
  localparam int unsigned AXI_BRESP_O_RESET = 0;
  localparam int unsigned AXI_BUSER_O_RESET = 0;
  localparam int unsigned AXI_RID_O_RESET = 0;
  localparam int unsigned AXI_RDATA_O_RESET = 0;
  localparam int unsigned AXI_RRESP_O_RESET = 0;
  localparam int unsigned AXI_RLAST_O_RESET = 0;
  localparam int unsigned AXI_RUSER_O_RESET = 0;
  localparam int unsigned NOC_REQ_VALID_O_RESET = 0;
  localparam int unsigned NOC_REQ_FLIT_O_RESET = 0;
  localparam int unsigned NOC_RSP_CREDIT_O_RESET = 0;
  localparam int unsigned CSR_BID_O_RESET = 0;
  localparam int unsigned CSR_BRESP_O_RESET = 0;
  localparam int unsigned CSR_BUSER_O_RESET = 0;
  localparam int unsigned CSR_RID_O_RESET = 0;
  localparam int unsigned CSR_RDATA_O_RESET = 0;
  localparam int unsigned CSR_RRESP_O_RESET = 0;
  localparam int unsigned CSR_RLAST_O_RESET = 0;
  localparam int unsigned CSR_RUSER_O_RESET = 0;
  localparam int unsigned NOC_REQ_CREDIT_O_RESET = 0;
  localparam int unsigned AXI_AWID_O_RESET = 0;
  localparam int unsigned AXI_AWADDR_O_RESET = 0;
  localparam int unsigned AXI_AWLEN_O_RESET = 0;
  localparam int unsigned AXI_AWSIZE_O_RESET = 0;
  localparam int unsigned AXI_AWBURST_O_RESET = 0;
  localparam int unsigned AXI_AWCACHE_O_RESET = 0;
  localparam int unsigned AXI_AWLOCK_O_RESET = 0;
  localparam int unsigned AXI_AWPROT_O_RESET = 0;
  localparam int unsigned AXI_AWREGION_O_RESET = 0;
  localparam int unsigned AXI_AWUSER_O_RESET = 0;
  localparam int unsigned AXI_AWQOS_O_RESET = 0;
  localparam int unsigned AXI_WDATA_O_RESET = 0;
  localparam int unsigned AXI_WSTRB_O_RESET = 0;
  localparam int unsigned AXI_WLAST_O_RESET = 0;
  localparam int unsigned AXI_WUSER_O_RESET = 0;
  localparam int unsigned AXI_ARID_O_RESET = 0;
  localparam int unsigned AXI_ARADDR_O_RESET = 0;
  localparam int unsigned AXI_ARLEN_O_RESET = 0;
  localparam int unsigned AXI_ARSIZE_O_RESET = 0;
  localparam int unsigned AXI_ARBURST_O_RESET = 0;
  localparam int unsigned AXI_ARCACHE_O_RESET = 0;
  localparam int unsigned AXI_ARLOCK_O_RESET = 0;
  localparam int unsigned AXI_ARPROT_O_RESET = 0;
  localparam int unsigned AXI_ARREGION_O_RESET = 0;
  localparam int unsigned AXI_ARUSER_O_RESET = 0;
  localparam int unsigned AXI_ARQOS_O_RESET = 0;
  localparam int unsigned NOC_RSP_VALID_O_RESET = 0;
  localparam int unsigned NOC_RSP_FLIT_O_RESET = 0;

endpackage

`endif // NI_SIGNALS_PKG_SVH
